# Configuración Jekyll para GitHub Pages - OTEC Revolución Digital
title: "Revolución Digital OTEC"
description: "Transforma tu OTEC o desarrolla tu marca personal como relator. Digitalización integral para el sector capacitación en Chile"
url: "https://pixai2025.github.io"
baseurl: "/otec-revolucion-digital"
author: "OTEC Revolución Digital"
email: "contacto@otec-revolucion.com"

# SEO y Social Media
lang: es-CL
timezone: America/Santiago
google_analytics: G-0FSM0DWKCM
google_site_verification: "4S9g_F5rrTRPslAvDJji6MW_angDMRzCIwzZzgnJB2I"

# Meta tags por defecto
defaults:
  - scope:
      path: ""
    values:
      image: "/assets/images/otec-og-image.png"
      type: "website"

# Plugins de Jekyll
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

# Configuración SEO
seo:
  name: "Revolución Digital OTEC"
  type: "Organization"
  links:
    - "https://pixai2025.github.io/otec-revolucion-digital"

# Social Media
social:
  name: "OTEC Revolución Digital"
  links:
    - https://www.linkedin.com/company/otec-revolucion-digital
    - https://www.facebook.com/otecrevoluciondigital

# Configuración para GitHub Pages
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

# Excluir archivos del build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/

# Configuración de compresión
sass:
  style: compressed

# Configuración de colecciones (para futuras expansiones)
collections_dir: _collections

# Configuración de permalink
permalink: pretty
